### ISSUE TITLE
Nur eine Seite

### ISSUE THREAD

**Issue by L3P3** [Yarlswip/Verarschung#1]
schön seite in github aber wo ist andere seite in github?? hubhub

**Comment by L3P3** [comment]
hier ist link https://j4r3.l3p3.de/

**Comment by L3P3** [comment]
wenn localhost seite gut, musst committen alles und schreibe was andert

**Comment by L3P3** [comment]
und bei tekst was andert schreibe #1 an anfang, dan diese issue ist market

**Comment by L3P3** [comment]
da ist enkantment von issue, ist jetzt angriff 5

**Comment by L3P3** [comment]
Du kannst diesen Bericht schließen, da gelöst.

**Comment by Yarlswip** [comment]
:þ
