### ISSUE TITLE
Alter falsch

### ISSUE THREAD

**Issue by L3P3** [Yarlswip/Verarschung#5]
In "über mich" steht dass du 12 bist.
Und ich finde, dass du noch mehr über dich da erzählen kannst.

**Comment by LFF5644** [comment]
woher wollen sie wissen das das alter falsch ist stand da schon 2 jahre lang das gleiche alter?

**Comment by L3P3** [comment]
Weil ich es weiß!

**Comment by LFF5644** [comment]
.... ahh ja (er dennkt das er es weiss)
