### ISSUE TITLE
Logo ist am falsceh Platz

### ISSUE THREAD

**Issue by LFF5644** [Yarlswip/Verarschung#9]
logo ist am falschen platz ![Bildschirmfoto zu 2024-05-03 19-40-16](https://github.com/enderwip/Verarschung/assets/109358910/0a865f42-abcf-4499-bb34-66c1bedcd817)

wenn man das fenster aber in der größe ändert 
![Bildschirmfoto zu 2024-05-03 19-40-27](https://github.com/enderwip/Verarschung/assets/109358910/0cb13637-f2de-44fa-8707-1468dd2d7e55)

**Comment by Yarlswip** [comment]
Behoben
